/*
 * GymApp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ClientDto model module.
 * @module model/ClientDto
 * @version 1.0
 */
export class ClientDto {
  /**
   * Constructs a new <code>ClientDto</code>.
   * @alias module:model/ClientDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ClientDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClientDto} obj Optional instance to populate.
   * @return {module:model/ClientDto} The populated <code>ClientDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ClientDto();
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} username
 */
ClientDto.prototype.username = undefined;

/**
 * @member {String} password
 */
ClientDto.prototype.password = undefined;

