/*
 * GymApp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The EmailDto model module.
 * @module model/EmailDto
 * @version 1.0
 */
export class EmailDto {
  /**
   * Constructs a new <code>EmailDto</code>.
   * @alias module:model/EmailDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>EmailDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EmailDto} obj Optional instance to populate.
   * @return {module:model/EmailDto} The populated <code>EmailDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EmailDto();
      if (data.hasOwnProperty('to'))
        obj.to = ApiClient.convertToType(data['to'], 'String');
      if (data.hasOwnProperty('subject'))
        obj.subject = ApiClient.convertToType(data['subject'], 'String');
      if (data.hasOwnProperty('body'))
        obj.body = ApiClient.convertToType(data['body'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} to
 */
EmailDto.prototype.to = undefined;

/**
 * @member {String} subject
 */
EmailDto.prototype.subject = undefined;

/**
 * @member {String} body
 */
EmailDto.prototype.body = undefined;

