/*
 * GymApp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Client} from './Client';
import {Entrance} from './Entrance';

/**
 * The EntranceEvent model module.
 * @module model/EntranceEvent
 * @version 1.0
 */
export class EntranceEvent {
  /**
   * Constructs a new <code>EntranceEvent</code>.
   * @alias module:model/EntranceEvent
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>EntranceEvent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EntranceEvent} obj Optional instance to populate.
   * @return {module:model/EntranceEvent} The populated <code>EntranceEvent</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EntranceEvent();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('ownerId'))
        obj.ownerId = ApiClient.convertToType(data['ownerId'], 'String');
      if (data.hasOwnProperty('dateTime'))
        obj.dateTime = ApiClient.convertToType(data['dateTime'], 'Date');
      if (data.hasOwnProperty('clientId'))
        obj.clientId = ApiClient.convertToType(data['clientId'], 'String');
      if (data.hasOwnProperty('client'))
        obj.client = Client.constructFromObject(data['client']);
      if (data.hasOwnProperty('entranceId'))
        obj.entranceId = ApiClient.convertToType(data['entranceId'], 'String');
      if (data.hasOwnProperty('entrance'))
        obj.entrance = Entrance.constructFromObject(data['entrance']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
EntranceEvent.prototype.id = undefined;

/**
 * @member {String} ownerId
 */
EntranceEvent.prototype.ownerId = undefined;

/**
 * @member {Date} dateTime
 */
EntranceEvent.prototype.dateTime = undefined;

/**
 * @member {String} clientId
 */
EntranceEvent.prototype.clientId = undefined;

/**
 * @member {module:model/Client} client
 */
EntranceEvent.prototype.client = undefined;

/**
 * @member {String} entranceId
 */
EntranceEvent.prototype.entranceId = undefined;

/**
 * @member {module:model/Entrance} entrance
 */
EntranceEvent.prototype.entrance = undefined;

