/*
 * GymApp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GymUserDAO model module.
 * @module model/GymUserDAO
 * @version 1.0
 */
export class GymUserDAO {
  /**
   * Constructs a new <code>GymUserDAO</code>.
   * @alias module:model/GymUserDAO
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GymUserDAO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GymUserDAO} obj Optional instance to populate.
   * @return {module:model/GymUserDAO} The populated <code>GymUserDAO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GymUserDAO();
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('plainTextPassword'))
        obj.plainTextPassword = ApiClient.convertToType(data['plainTextPassword'], 'String');
      if (data.hasOwnProperty('userRoles'))
        obj.userRoles = ApiClient.convertToType(data['userRoles'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {String} email
 */
GymUserDAO.prototype.email = undefined;

/**
 * @member {String} plainTextPassword
 */
GymUserDAO.prototype.plainTextPassword = undefined;

/**
 * @member {Array.<String>} userRoles
 */
GymUserDAO.prototype.userRoles = undefined;

