/*
 * GymApp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PassBoughtEvent model module.
 * @module model/PassBoughtEvent
 * @version 1.0
 */
export class PassBoughtEvent {
  /**
   * Constructs a new <code>PassBoughtEvent</code>.
   * @alias module:model/PassBoughtEvent
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PassBoughtEvent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PassBoughtEvent} obj Optional instance to populate.
   * @return {module:model/PassBoughtEvent} The populated <code>PassBoughtEvent</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PassBoughtEvent();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('ownerId'))
        obj.ownerId = ApiClient.convertToType(data['ownerId'], 'String');
      if (data.hasOwnProperty('dateTime'))
        obj.dateTime = ApiClient.convertToType(data['dateTime'], 'Date');
      if (data.hasOwnProperty('passId'))
        obj.passId = ApiClient.convertToType(data['passId'], 'String');
      if (data.hasOwnProperty('clientId'))
        obj.clientId = ApiClient.convertToType(data['clientId'], 'String');
      if (data.hasOwnProperty('refresh'))
        obj.refresh = ApiClient.convertToType(data['refresh'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
PassBoughtEvent.prototype.id = undefined;

/**
 * @member {String} ownerId
 */
PassBoughtEvent.prototype.ownerId = undefined;

/**
 * @member {Date} dateTime
 */
PassBoughtEvent.prototype.dateTime = undefined;

/**
 * @member {String} passId
 */
PassBoughtEvent.prototype.passId = undefined;

/**
 * @member {String} clientId
 */
PassBoughtEvent.prototype.clientId = undefined;

/**
 * @member {Number} refresh
 */
PassBoughtEvent.prototype.refresh = undefined;

