/*
 * GymApp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GymApp);
  }
}(this, function(expect, GymApp) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GymApp.ClientsApi();
  });

  describe('(package)', function() {
    describe('ClientsApi', function() {
      describe('apiClientsGet', function() {
        it('should call apiClientsGet successfully', function(done) {
          // TODO: uncomment apiClientsGet call and complete the assertions
          /*

          instance.apiClientsGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(GymApp.Client);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiClientsGetByOwnerIdOwnerIdGet', function() {
        it('should call apiClientsGetByOwnerIdOwnerIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiClientsGetByOwnerIdOwnerIdGet call and complete the assertions
          /*

          instance.apiClientsGetByOwnerIdOwnerIdGet(ownerId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GymApp.Client);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiClientsIdDelete', function() {
        it('should call apiClientsIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for apiClientsIdDelete call
          /*

          instance.apiClientsIdDelete(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiClientsIdGet', function() {
        it('should call apiClientsIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiClientsIdGet call and complete the assertions
          /*

          instance.apiClientsIdGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GymApp.Client);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiClientsIdPut', function() {
        it('should call apiClientsIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for apiClientsIdPut call
          /*
          var opts = {};

          instance.apiClientsIdPut(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiClientsPost', function() {
        it('should call apiClientsPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiClientsPost call and complete the assertions
          /*
          var opts = {};

          instance.apiClientsPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GymApp.Client);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
