/*
 * GymApp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GymApp);
  }
}(this, function(expect, GymApp) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GymApp.EntranceEventsApi();
  });

  describe('(package)', function() {
    describe('EntranceEventsApi', function() {
      describe('apiEntranceEventsGet', function() {
        it('should call apiEntranceEventsGet successfully', function(done) {
          // TODO: uncomment apiEntranceEventsGet call and complete the assertions
          /*

          instance.apiEntranceEventsGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(GymApp.EntranceEvent);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiEntranceEventsIdDelete', function() {
        it('should call apiEntranceEventsIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for apiEntranceEventsIdDelete call
          /*

          instance.apiEntranceEventsIdDelete(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiEntranceEventsIdGet', function() {
        it('should call apiEntranceEventsIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiEntranceEventsIdGet call and complete the assertions
          /*

          instance.apiEntranceEventsIdGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GymApp.EntranceEvent);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiEntranceEventsIdPut', function() {
        it('should call apiEntranceEventsIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for apiEntranceEventsIdPut call
          /*
          var opts = {};

          instance.apiEntranceEventsIdPut(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiEntranceEventsPost', function() {
        it('should call apiEntranceEventsPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiEntranceEventsPost call and complete the assertions
          /*
          var opts = {};

          instance.apiEntranceEventsPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GymApp.EntranceEvent);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
