/*
 * GymApp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GymApp);
  }
}(this, function(expect, GymApp) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GymApp.EntrancesApi();
  });

  describe('(package)', function() {
    describe('EntrancesApi', function() {
      describe('apiEntrancesGet', function() {
        it('should call apiEntrancesGet successfully', function(done) {
          // TODO: uncomment apiEntrancesGet call and complete the assertions
          /*

          instance.apiEntrancesGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(GymApp.Entrance);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiEntrancesIdDelete', function() {
        it('should call apiEntrancesIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for apiEntrancesIdDelete call
          /*

          instance.apiEntrancesIdDelete(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiEntrancesIdGet', function() {
        it('should call apiEntrancesIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiEntrancesIdGet call and complete the assertions
          /*

          instance.apiEntrancesIdGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GymApp.Entrance);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiEntrancesIdPut', function() {
        it('should call apiEntrancesIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for apiEntrancesIdPut call
          /*
          var opts = {};

          instance.apiEntrancesIdPut(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiEntrancesPost', function() {
        it('should call apiEntrancesPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiEntrancesPost call and complete the assertions
          /*
          var opts = {};

          instance.apiEntrancesPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GymApp.Entrance);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
