/*
 * GymApp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GymApp);
  }
}(this, function(expect, GymApp) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GymApp.PassesApi();
  });

  describe('(package)', function() {
    describe('PassesApi', function() {
      describe('apiPassesGet', function() {
        it('should call apiPassesGet successfully', function(done) {
          // TODO: uncomment apiPassesGet call and complete the assertions
          /*

          instance.apiPassesGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(GymApp.Pass);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiPassesIdDelete', function() {
        it('should call apiPassesIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for apiPassesIdDelete call
          /*

          instance.apiPassesIdDelete(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiPassesIdGet', function() {
        it('should call apiPassesIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiPassesIdGet call and complete the assertions
          /*

          instance.apiPassesIdGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GymApp.Pass);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiPassesIdPut', function() {
        it('should call apiPassesIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for apiPassesIdPut call
          /*
          var opts = {};

          instance.apiPassesIdPut(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiPassesPost', function() {
        it('should call apiPassesPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiPassesPost call and complete the assertions
          /*
          var opts = {};

          instance.apiPassesPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GymApp.Pass);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
