/*
 * GymApp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GymApp);
  }
}(this, function(expect, GymApp) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GymApp.PassBoughtEventsApi();
  });

  describe('(package)', function() {
    describe('PassBoughtEventsApi', function() {
      describe('apiPassBoughtEventsDeactivatePassPassBoughtEventIdPut', function() {
        it('should call apiPassBoughtEventsDeactivatePassPassBoughtEventIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for apiPassBoughtEventsDeactivatePassPassBoughtEventIdPut call and complete the assertions
          /*

          instance.apiPassBoughtEventsDeactivatePassPassBoughtEventIdPut(passBoughtEventId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GymApp.PassBoughtEvent);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiPassBoughtEventsExtendPassValidityPassBoughtEventIdPut', function() {
        it('should call apiPassBoughtEventsExtendPassValidityPassBoughtEventIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for apiPassBoughtEventsExtendPassValidityPassBoughtEventIdPut call and complete the assertions
          /*
          var opts = {};

          instance.apiPassBoughtEventsExtendPassValidityPassBoughtEventIdPut(passBoughtEventId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GymApp.PassBoughtEvent);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiPassBoughtEventsGet', function() {
        it('should call apiPassBoughtEventsGet successfully', function(done) {
          // TODO: uncomment apiPassBoughtEventsGet call and complete the assertions
          /*

          instance.apiPassBoughtEventsGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(GymApp.PassBoughtEvent);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiPassBoughtEventsGetActivePassesClientIdGet', function() {
        it('should call apiPassBoughtEventsGetActivePassesClientIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiPassBoughtEventsGetActivePassesClientIdGet call and complete the assertions
          /*

          instance.apiPassBoughtEventsGetActivePassesClientIdGet(clientId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(GymApp.PassBoughtEvent);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiPassBoughtEventsIdDelete', function() {
        it('should call apiPassBoughtEventsIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for apiPassBoughtEventsIdDelete call
          /*

          instance.apiPassBoughtEventsIdDelete(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiPassBoughtEventsIdGet', function() {
        it('should call apiPassBoughtEventsIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiPassBoughtEventsIdGet call and complete the assertions
          /*

          instance.apiPassBoughtEventsIdGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GymApp.PassBoughtEvent);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiPassBoughtEventsIdPut', function() {
        it('should call apiPassBoughtEventsIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for apiPassBoughtEventsIdPut call
          /*
          var opts = {};

          instance.apiPassBoughtEventsIdPut(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiPassBoughtEventsPost', function() {
        it('should call apiPassBoughtEventsPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiPassBoughtEventsPost call and complete the assertions
          /*
          var opts = {};

          instance.apiPassBoughtEventsPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GymApp.PassBoughtEvent);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
