/*
 * GymApp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GymApp);
  }
}(this, function(expect, GymApp) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GymApp.SectorsApi();
  });

  describe('(package)', function() {
    describe('SectorsApi', function() {
      describe('apiSectorsCheckIfActiveGet', function() {
        it('should call apiSectorsCheckIfActiveGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiSectorsCheckIfActiveGet call and complete the assertions
          /*
          var opts = {};

          instance.apiSectorsCheckIfActiveGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(GymApp.PassBoughtEvent);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiSectorsGet', function() {
        it('should call apiSectorsGet successfully', function(done) {
          // TODO: uncomment apiSectorsGet call and complete the assertions
          /*

          instance.apiSectorsGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(GymApp.Sector);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiSectorsGetActiveSectorsClientIdGet', function() {
        it('should call apiSectorsGetActiveSectorsClientIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiSectorsGetActiveSectorsClientIdGet call and complete the assertions
          /*

          instance.apiSectorsGetActiveSectorsClientIdGet(clientId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(GymApp.PassBoughtEvent);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiSectorsIdDelete', function() {
        it('should call apiSectorsIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for apiSectorsIdDelete call
          /*

          instance.apiSectorsIdDelete(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiSectorsIdGet', function() {
        it('should call apiSectorsIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiSectorsIdGet call and complete the assertions
          /*

          instance.apiSectorsIdGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GymApp.Sector);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiSectorsIdPut', function() {
        it('should call apiSectorsIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for apiSectorsIdPut call
          /*
          var opts = {};

          instance.apiSectorsIdPut(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiSectorsPost', function() {
        it('should call apiSectorsPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiSectorsPost call and complete the assertions
          /*
          var opts = {};

          instance.apiSectorsPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GymApp.Sector);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
