/*
 * GymApp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The WeatherForecast model module.
 * @module model/WeatherForecast
 * @version 1.0
 */
export class WeatherForecast {
  /**
   * Constructs a new <code>WeatherForecast</code>.
   * @alias module:model/WeatherForecast
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>WeatherForecast</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WeatherForecast} obj Optional instance to populate.
   * @return {module:model/WeatherForecast} The populated <code>WeatherForecast</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WeatherForecast();
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('temperatureC'))
        obj.temperatureC = ApiClient.convertToType(data['temperatureC'], 'Number');
      if (data.hasOwnProperty('temperatureF'))
        obj.temperatureF = ApiClient.convertToType(data['temperatureF'], 'Number');
      if (data.hasOwnProperty('summary'))
        obj.summary = ApiClient.convertToType(data['summary'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Date} _date
 */
WeatherForecast.prototype._date = undefined;

/**
 * @member {Number} temperatureC
 */
WeatherForecast.prototype.temperatureC = undefined;

/**
 * @member {Number} temperatureF
 */
WeatherForecast.prototype.temperatureF = undefined;

/**
 * @member {String} summary
 */
WeatherForecast.prototype.summary = undefined;

