/*
 * GymApp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GymApp);
  }
}(this, function(expect, GymApp) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Client', function() {
      beforeEach(function() {
        instance = new GymApp.Client();
      });

      it('should create an instance of Client', function() {
        // TODO: update the code to test Client
        expect(instance).to.be.a(GymApp.Client);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property ownerId (base name: "ownerId")', function() {
        // TODO: update the code to test the property ownerId
        expect(instance).to.have.property('ownerId');
        // expect(instance.ownerId).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property surname (base name: "surname")', function() {
        // TODO: update the code to test the property surname
        expect(instance).to.have.property('surname');
        // expect(instance.surname).to.be(expectedValueLiteral);
      });

      it('should have the property phoneNumber (base name: "phoneNumber")', function() {
        // TODO: update the code to test the property phoneNumber
        expect(instance).to.have.property('phoneNumber');
        // expect(instance.phoneNumber).to.be(expectedValueLiteral);
      });

      it('should have the property passBoughtEvents (base name: "passBoughtEvents")', function() {
        // TODO: update the code to test the property passBoughtEvents
        expect(instance).to.have.property('passBoughtEvents');
        // expect(instance.passBoughtEvents).to.be(expectedValueLiteral);
      });

      it('should have the property entranceEvents (base name: "entranceEvents")', function() {
        // TODO: update the code to test the property entranceEvents
        expect(instance).to.have.property('entranceEvents');
        // expect(instance.entranceEvents).to.be(expectedValueLiteral);
      });

    });
  });

}));
