/*
 * GymApp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GymApp);
  }
}(this, function(expect, GymApp) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GymUserDAO', function() {
      beforeEach(function() {
        instance = new GymApp.GymUserDAO();
      });

      it('should create an instance of GymUserDAO', function() {
        // TODO: update the code to test GymUserDAO
        expect(instance).to.be.a(GymApp.GymUserDAO);
      });

      it('should have the property email (base name: "email")', function() {
        // TODO: update the code to test the property email
        expect(instance).to.have.property('email');
        // expect(instance.email).to.be(expectedValueLiteral);
      });

      it('should have the property plainTextPassword (base name: "plainTextPassword")', function() {
        // TODO: update the code to test the property plainTextPassword
        expect(instance).to.have.property('plainTextPassword');
        // expect(instance.plainTextPassword).to.be(expectedValueLiteral);
      });

      it('should have the property userRoles (base name: "userRoles")', function() {
        // TODO: update the code to test the property userRoles
        expect(instance).to.have.property('userRoles');
        // expect(instance.userRoles).to.be(expectedValueLiteral);
      });

    });
  });

}));
