/*
 * GymApp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GymApp);
  }
}(this, function(expect, GymApp) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Pass', function() {
      beforeEach(function() {
        instance = new GymApp.Pass();
      });

      it('should create an instance of Pass', function() {
        // TODO: update the code to test Pass
        expect(instance).to.be.a(GymApp.Pass);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property ownerId (base name: "ownerId")', function() {
        // TODO: update the code to test the property ownerId
        expect(instance).to.have.property('ownerId');
        // expect(instance.ownerId).to.be(expectedValueLiteral);
      });

      it('should have the property passName (base name: "passName")', function() {
        // TODO: update the code to test the property passName
        expect(instance).to.have.property('passName');
        // expect(instance.passName).to.be(expectedValueLiteral);
      });

      it('should have the property passDescription (base name: "passDescription")', function() {
        // TODO: update the code to test the property passDescription
        expect(instance).to.have.property('passDescription');
        // expect(instance.passDescription).to.be(expectedValueLiteral);
      });

      it('should have the property price (base name: "price")', function() {
        // TODO: update the code to test the property price
        expect(instance).to.have.property('price');
        // expect(instance.price).to.be(expectedValueLiteral);
      });

      it('should have the property duration (base name: "duration")', function() {
        // TODO: update the code to test the property duration
        expect(instance).to.have.property('duration');
        // expect(instance.duration).to.be(expectedValueLiteral);
      });

      it('should have the property passBoughtEvents (base name: "passBoughtEvents")', function() {
        // TODO: update the code to test the property passBoughtEvents
        expect(instance).to.have.property('passBoughtEvents');
        // expect(instance.passBoughtEvents).to.be(expectedValueLiteral);
      });

      it('should have the property entrances (base name: "entrances")', function() {
        // TODO: update the code to test the property entrances
        expect(instance).to.have.property('entrances');
        // expect(instance.entrances).to.be(expectedValueLiteral);
      });

    });
  });

}));
