/*
 * GymApp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GymApp);
  }
}(this, function(expect, GymApp) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Sector', function() {
      beforeEach(function() {
        instance = new GymApp.Sector();
      });

      it('should create an instance of Sector', function() {
        // TODO: update the code to test Sector
        expect(instance).to.be.a(GymApp.Sector);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property ownerId (base name: "ownerId")', function() {
        // TODO: update the code to test the property ownerId
        expect(instance).to.have.property('ownerId');
        // expect(instance.ownerId).to.be(expectedValueLiteral);
      });

      it('should have the property sectorName (base name: "sectorName")', function() {
        // TODO: update the code to test the property sectorName
        expect(instance).to.have.property('sectorName');
        // expect(instance.sectorName).to.be(expectedValueLiteral);
      });

      it('should have the property gymId (base name: "gymId")', function() {
        // TODO: update the code to test the property gymId
        expect(instance).to.have.property('gymId');
        // expect(instance.gymId).to.be(expectedValueLiteral);
      });

      it('should have the property gym (base name: "gym")', function() {
        // TODO: update the code to test the property gym
        expect(instance).to.have.property('gym');
        // expect(instance.gym).to.be(expectedValueLiteral);
      });

      it('should have the property entrances (base name: "entrances")', function() {
        // TODO: update the code to test the property entrances
        expect(instance).to.have.property('entrances');
        // expect(instance.entrances).to.be(expectedValueLiteral);
      });

    });
  });

}));
