/*
 * GymApp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GymApp);
  }
}(this, function(expect, GymApp) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('WeatherForecast', function() {
      beforeEach(function() {
        instance = new GymApp.WeatherForecast();
      });

      it('should create an instance of WeatherForecast', function() {
        // TODO: update the code to test WeatherForecast
        expect(instance).to.be.a(GymApp.WeatherForecast);
      });

      it('should have the property _date (base name: "date")', function() {
        // TODO: update the code to test the property _date
        expect(instance).to.have.property('_date');
        // expect(instance._date).to.be(expectedValueLiteral);
      });

      it('should have the property temperatureC (base name: "temperatureC")', function() {
        // TODO: update the code to test the property temperatureC
        expect(instance).to.have.property('temperatureC');
        // expect(instance.temperatureC).to.be(expectedValueLiteral);
      });

      it('should have the property temperatureF (base name: "temperatureF")', function() {
        // TODO: update the code to test the property temperatureF
        expect(instance).to.have.property('temperatureF');
        // expect(instance.temperatureF).to.be(expectedValueLiteral);
      });

      it('should have the property summary (base name: "summary")', function() {
        // TODO: update the code to test the property summary
        expect(instance).to.have.property('summary');
        // expect(instance.summary).to.be(expectedValueLiteral);
      });

    });
  });

}));
